apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infrastructure

resources:
  - postgres-operator.yaml
  - postgres-cluster.yaml

commonLabels:
  app.kubernetes.io/part-of: maetwix-cluster
